// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBMLIOIs3CV1eK3G9QnPYxgGW_qn7LN0k',
    appId: '1:884641086620:web:92fabd8c8f6eb29e9e0159',
    messagingSenderId: '884641086620',
    projectId: 'fireapp-61713',
    authDomain: 'fireapp-61713.firebaseapp.com',
    storageBucket: 'fireapp-61713.appspot.com',
    measurementId: 'G-JPSNSGQG7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcu3V_eRGflrdfA041v9trYUcNDbEwoRo',
    appId: '1:884641086620:android:cc9d847ed89ba59f9e0159',
    messagingSenderId: '884641086620',
    projectId: 'fireapp-61713',
    storageBucket: 'fireapp-61713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3_9q7tvjvHQruIsiRjtKV4H2LqW45WWI',
    appId: '1:884641086620:ios:a265aa4a204c63fb9e0159',
    messagingSenderId: '884641086620',
    projectId: 'fireapp-61713',
    storageBucket: 'fireapp-61713.appspot.com',
    iosClientId: '884641086620-bohv7m0nuegfkrb0ihlqj7m0pjeomjsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutternew',
  );
}
